# Schema for the configuration files of the BFI SSO module.
bfi_mini_orange.settings:
  type: config_object
  label: 'BFI mini orange settings'
  mapping:
    enable_redirect_user_login:
      type: boolean
      label: 'Enable user login redirect'
